#!/usr/bin/env python3
"""
Generate C test vectors from the Python reference implementation.

The C core and the reference have to agree byte for byte. Rather than
hoping, the Python side emits what it produces and the C tests assert
against it. Regenerate with:

    python3 tests/gen_vectors.py
"""
import pathlib
import sys
import zlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "sim"))

from loraitp import aescmac, frames as F, gf256, phy  # noqa: E402
from loraitp.session import frame_ordinal  # noqa: E402

OUT = ROOT / "tests" / "vectors" / "vectors.h"


def carr(name, data):
    body = ",".join(f"0x{b:02x}" for b in data)
    return f"static const uint8_t {name}[] = {{{body}}};\n"


def main():
    L = ["/* Generated by tests/gen_vectors.py - do not edit. */\n",
         "#ifndef LORAITP_TEST_VECTORS_H\n#define LORAITP_TEST_VECTORS_H\n",
         "#include <stdint.h>\n\n"]

    # --- time on air, straight from tools/airtime.py
    L.append("typedef struct { uint8_t pl, sf, cr; uint32_t bw, us; }"
             " toa_vec_t;\n")
    rows = []
    for sf in range(7, 13):
        for pl in (16, 51, 100, 200, 251):
            us = round(phy.time_on_air_ms(pl, sf, 125000, 1) * 1000)
            rows.append(f"{{{pl},{sf},1,125000,{us}}}")
    for pl in (51, 200):
        for bw in (250000, 20830):
            us = round(phy.time_on_air_ms(pl, 12, bw, 1) * 1000)
            rows.append(f"{{{pl},12,1,{bw},{us}}}")
    L.append(f"static const toa_vec_t toa_vecs[] = {{{','.join(rows)}}};\n")
    L.append(f"#define N_TOA_VECS {len(rows)}\n\n")

    # --- META, exactly as the reference encodes it
    m = F.Meta(sid=7, img_id=1842, layer=1, img_len=10000, chunk=196,
               codec=2, crc32=0xDEADBEEF, width=320, height=240,
               flags=F.F_BROADCAST | F.F_PARITY_PRESENT, block=128,
               n_parity=39, nonce=bytes([1, 2, 3, 4]),
               tlvs=[(0x01, b"DL1ABC")])
    L.append(carr("meta_expected", m.encode()))
    L.append(f"#define META_N_CHUNKS {m.n_chunks}\n"
             f"#define META_N_BLOCKS {m.n_blocks}\n"
             f"#define META_TOTAL_FRAMES {m.total_frames}\n\n")

    ords = [frame_ordinal(m, s, False) for s in (0, 1, 127, 128, 129)]
    ords += [frame_ordinal(m, s, True) for s in (0, 38, 39)]
    L.append(f"static const uint32_t ordinal_expected[] = "
             f"{{{','.join(str(o) for o in ords)}}};\n\n")

    # --- DATA
    d = F.Data(sid=7, seq=513, payload=bytes(range(16)))
    L.append(carr("data_expected", d.encode()))

    # --- STAT, both encodings
    missing = [131, 137, 168, 255]
    for name, enc in (("stat_bitmap", F.ENC_BITMAP), ("stat_list", F.ENC_LIST)):
        s = F.Stat(sid=7, block=1, round=2, enc=enc, rssi=-98, snr_qdb=-40,
                   missing=missing, base=128)
        L.append(carr(f"{name}_expected", s.encode()))
    L.append(f"static const uint16_t stat_missing[] = "
             f"{{{','.join(str(x) for x in missing)}}};\n")
    L.append(f"#define STAT_N_MISSING {len(missing)}\n"
             f"#define STAT_BASE 128\n\n")

    def spread(n, block=128):
        return [round(i * (block - 1) / (n - 1)) for i in range(n)] if n > 1 \
               else [block - 1]
    cross = next(n for n in range(1, 40)
                 if F.Stat.choose_encoding(spread(n), 0, 128) == F.ENC_BITMAP)
    L.append(f"#define STAT_CROSSOVER {cross}\n\n")

    # --- CRC-32 against zlib
    payload = bytes((i * 37) & 0xFF for i in range(1000))
    L.append(carr("crc_input", payload))
    L.append(f"#define CRC_EXPECTED 0x{zlib.crc32(payload) & 0xFFFFFFFF:08x}u\n\n")

    # --- CMAC, RFC 4493
    key = bytes.fromhex("2b7e151628aed2a6abf7158809cf4f3c")
    L.append(carr("cmac_key", key))
    msg = bytes.fromhex("6bc1bee22e409f96e93d7e117393172a")
    L.append(carr("cmac_msg16", msg))
    L.append(carr("cmac_tag16", aescmac.cmac(key, msg)))
    L.append(carr("cmac_tag0", aescmac.cmac(key, b"")))
    L.append("\n")

    # --- Reed-Solomon
    k, r, clen = 12, 5, 32
    data = [bytes(((i * 31 + j * 7) & 0xFF) for j in range(clen))
            for i in range(k)]
    par = gf256.encode(data, r)
    L.append(carr("rs_data", b"".join(data)))
    L.append(carr("rs_parity", b"".join(par)))
    L.append(f"#define RS_K {k}\n#define RS_R {r}\n#define RS_CHUNK {clen}\n\n")

    L.append("#endif\n")
    OUT.write_text("".join(L))
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes, {len(rows)} ToA vectors)")


if __name__ == "__main__":
    main()
